# Generated by Django 3.1.6 on 2021-04-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('pokemon_id', models.AutoField(primary_key=True, serialize=False)),
                ('pokemon_name', models.TextField(max_length=255)),
                ('pokemon_type', models.CharField(max_length=50)),
                ('pokemon_species', models.TextField(max_length=50)),
                ('pokemon_height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pokemon_weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pokemon_abilities', models.TextField(max_length=255)),
                ('pokemon_entrydate', models.DateField(verbose_name='Entry Date')),
            ],
        ),
    ]
