# Generated by Django 3.1.6 on 2021-04-28 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedex',
            name='pokemon_updatedat',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='pokemon_entrydate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Entry'),
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='pokemon_height',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='pokemon_weight',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
